### ISSUE TITLE
Problem with links between collection and items

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#121]
Nr. 410000224 should belong to collection 410000180 (and not 410000175)

Nr. 410000354 should belong to collection 410000333 (and not 410000180)

It is unclear why the link with the collection cannot be changed or cannot be made in the first place.

**Comment by xhero** [comment]
@cgueggi and @lpugin 
I pushed a fix for this. there still is the problem with the data. I see (as of today) that there are 32 collections affected. It is very easy for me to make a script that cycles through the elements of a collection and adds them back, but what about ordering? I can order by ID but I am not sure if it is correct.
Also the collections contain a spurious "=  18" (generated by the incorrect 772 code) which has to be fixed with a script (I will fix this once we add back the missing links).
