### ISSUE TITLE
Select Cascade for Relator Codes cannot be deleted

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#123]
Removing a repeatable subfield can easily be achieve by leaving it blank. However, this is not possible with subfield inputed with select (see 730 $4). We need a possibility to remove these fields ([-] button?)

**Comment by xhero** [comment]
730 has no $4 configured... Do you have a link to a ms?

**Comment by xhero** [comment]
Ok found it in 700. If I change the select code so when you select "-- Select --" it clears the field? It works for the sublist, but not the toplevel list.

**Comment by xhero** [comment]
The problem is that when you load the page all the selects are on the default. I see why we should add -.
I still like the idea of using the select instead of adding a button (which is not simple at all). I could have the select that actually shows the correct item instead of the default (I think, I have to try it)
