### ISSUE TITLE
Sorting after shelf mark wrong

### ISSUE THREAD

**Issue by cgueggi** [rism-ch/muscat#150]
f. e. search for CH-Lz (in "siglum contains") -> sort by shelf mark:
result: Mus 100, Mus 128 [...], Mus 1950, Mus 234, Mus 235, Mus 243 etc.
Seems to sort just by the first chiffre.
Maybe to discuss personally

**Comment by xhero** [comment]
It makes sense because it is a plain alphabetical ordering in the whole string. But since it is handled by solr I am not sure there is an easy solution. We need to check.

<div>-------- Messaggio originale --------</div><div>Da: cgueggi <notifications@github.com> </div><div>Data:01/07/2015  15:14  (GMT+01:00) </div><div>A: rism-ch/muscat <muscat@noreply.github.com> </div><div>Oggetto: [muscat] Sorting after shelf mark wrong (#150) </div><div>
</div>f. e. search for CH-Lz (in "siglum contains") -> sort by shelf mark:
result: Mus 100, Mus 128 [...], Mus 1950, Mus 234, Mus 235, Mus 243 etc.
Seems to sort just by the first chiffre.
Maybe to discuss personally

**Comment by cgueggi** [comment]
Ok. Thanks. But it's not normal, when the sortion system ist like this: 1, 10, 101, 10001 etc.

**Comment by xhero** [comment]
Well it is because the system thinks of them as letters, like aa ab bb, if it was only numbers it would work, I guess it fails because it is a mixture of letters and numbers. I will look into this 

<div>-------- Messaggio originale --------</div><div>Da: cgueggi <notifications@github.com> </div><div>Data:01/07/2015  15:26  (GMT+01:00) </div><div>A: rism-ch/muscat <muscat@noreply.github.com> </div><div>Cc: xhero <rwz@xhero.org> </div><div>Oggetto: Re: [muscat] Sorting after shelf mark wrong (#150) </div><div>
</div>Ok. Thanks. But it's not normal, when the sortion system ist like this: 1, 10, 101, 10001 etc.

**Comment by lpugin** [comment]
Nothing wrong here. (This should be taken into account when shelf marks are created.)
