### ISSUE TITLE
Update configuration for 594 ($b and $c)

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#340]
@HirschSt do you have a list of instruments from Kallisto for $b?

**Comment by HirschSt** [comment]
Hi,

a list with all entries in 594 is available at
http://dl.rism.info/reports/scoring.xls. Because this field is not
normalized now it contains "many" false entries, maybe you can stay in
contact with Jennifer who is also working on a list for 594.

Hope this helps.

Stephan

2016-05-10 17:07 GMT+02:00 Laurent Pugin <notifications@github.com>:

> @HirschSt <https://github.com/HirschSt> do you have a list of instruments
> from Kallisto for $b?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/rism-ch/muscat/issues/340>
>



-- 

Répertoire International des Sources Musicales
Stephan Hirsch
IT-Manager
Zentralredaktion
Sophienstraße 26
D-60487 Frankfurt am Main
Tel: +49 (0) 69 70 62 31
Fax: +49 (0) 69 70 60 26
http://www.rism.info

**Comment by lpugin** [comment]
Thanks for the list. It is obviously too long and too messy for having this in the configuration. @xhero we will need a Solr autocomplete.

**Comment by xhero** [comment]
We also need to convert our list to 594 - how should we proceed?

**Comment by lpugin** [comment]
For now we will have only 598. See #192

**Comment by xhero** [comment]
I added 594 to the autocomplete; I would need the labels for 594 $a, b, c for the editor

**Comment by lpugin** [comment]
@HirschSt what is used in Kallisto?
@xhero $a has to be dropped and generated in to_external

**Comment by xhero** [comment]
@lpugin it is just a concatenation of the $b and $c?
