### ISSUE TITLE
Finalized 510 and 596

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#403]
Both needs $a and $b fields. Also has to be fixed in the export?

**Comment by lpugin** [comment]
As far as I understood the discussion, what we should have is

* 510 instead of 035 (or 490 in the opac)
* Have 510 $a for the series (A/I, B/I) as a drop-down list and $b for the former ID (e.g,. "M 525")
* Have 596 splited in $a and $b in the same way

It this all good? Once this has be check with Jennifer, I will do the adjustments to the various configurations

**Comment by HirschSt** [comment]
That's somehow confusing for me:
- why should we have both, 510 and 596?
- 035 is defined as local number, because some working groups are eager to continue with the now used rismid-system aside from id. It's not restricted to A/I-numbers.
- 490 is an indicator series (especially for the opac facet); often in B/I we do not have an special id (https://opac.rism.info/id/rismid/00000993108967?format=marc) too.

I think we should collect all options and keep in mind the existent migration before we make changes to the actual configuration.

**Comment by lpugin** [comment]
> why should we have both, 510 and 596?

You can look at the discussion with RSH. 510 indicates that the record is part of a series ($a A/I) and for older titles also the previous id ($b M 525). 596 is an indication for referring to another titles.

> 035 is defined as local number

This remains. Users can use them as they want (apparently the SBB want to continue to add their own internal ids there)

> often in B/I we do not have an special id

This is fine. In such case we have only $a. It is going to be the case for new records anyway.

**Comment by HirschSt** [comment]
Ok, now I am a bit updated:
- 510 in the export now contains series in $a and location in $c, it's not in the configuration
- Existing references to series in 510 are going to 691, see http://muscat-dev.rism.info/admin/sources/456052603 or http://muscat-dev.rism.info/admin/sources/456050223

Considering both tags (510 as reference to the series and 691 as bibliographic reference to another title) we have both, so I doubt if we really need 596...

**Comment by lpugin** [comment]
I am changing the configuration. Could you check with Jennifer and RSH for 596? Thanks

**Comment by lpugin** [comment]
OK, the 510 part is done. Waiting for 596

**Comment by xhero** [comment]
There is nothing I have to do in the import right? This is exported data + conf?

**Comment by lpugin** [comment]
No, nothing to tweak
