### ISSUE TITLE
Verifying splitting of 852 into links

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#426]
See http://muscat-dev.rism.info/admin/sources/1000000668
I think we still have erroneous 856 created during the splitting of A/I data

**Comment by xhero** [comment]
Yes we do, the correct code did not make it into 3.6.0 and is in 3.6.1


Inviato dal mio dispositivo Samsung

-------- Messaggio originale --------
Da: Laurent Pugin <notifications@github.com> 
Data: 12/10/2016  17:09  (GMT+01:00) 
A: rism-ch/muscat <muscat@noreply.github.com> 
Cc: xhero <rwz@xhero.org>, Mention <mention@noreply.github.com> 
Oggetto: Re: [rism-ch/muscat] Verifying splitting of 852 into links (#426) 

Assigned #426 to @xhero.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/rism-ch/muscat","title":"rism-ch/muscat","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/rism-ch/muscat"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Assigned #426 to @xhero."}],"action":{"name":"View Issue","url":"https://github.com/rism-ch/muscat/issues/426#event-821123547"}}}

**Comment by lpugin** [comment]
OK, thanks. I overlooked it.
