### ISSUE TITLE
Make title in StandardTitle writeable

### ISSUE THREAD

**Issue by HirschSt** [rism-ch/muscat#489]
@xhero 
Any reason why we have this readonly?

https://github.com/rism-ch/muscat/blob/7f5568b9cee6ab56bd38a067f2575ceffaa2d17c/app/admin/standard_title.rb#L156

**Comment by xhero** [comment]
Because changing that would require an update to all the sources connected

**Comment by lpugin** [comment]
Yes, I think we need to be careful here. It would leave it like this.

**Comment by HirschSt** [comment]
Triggering a bulk of linked sources is a problem, but it isn't acceptable that editors are not able to change such an important category, so we need to look foward for another solution.

**Comment by HirschSt** [comment]
Comment from user side: http://muscat.rism.info/admin/sources/1001010165

**Comment by xhero** [comment]
Well to be doable it certainly is, we have all the infrastructure in place also, it is done for People for example. If it is desirable and a request, we can make the change.

**Comment by jenniferward** [comment]
Yes, this is 100% desirable and necessary for ZR staff in order to maintain a clean index of titles and text incipits. These are our authority files after all. The autocomplete doesn't allow you to create new entries when there are differences between lowercase and uppercase letters and records must be created "incorrectly." For example, entering "Das Rosenstöcklein steht in Flor" links automatically to the record "Das Rosenstöcklein steht in flor" and a correct entry with "Flor" is not possible. Correcting this "flor/Flor" error is not possible. This creates more and more incorrect records in the database. 

Changing headings in **all** other indexes is possible: in personal names, secondary literature, subject headings, liturgical festivals, etc. we can change the main heading and then it will automatically be changed in all the records where the term appears. This is a good thing because then you don't have to change dozens or hundreds of records by hand (as you had to in Kallisto). This is an advantage of Muscat. For example, we might discover a typo in a subject heading or we might change spelling errors, content errors, or errors in the form of the heading. If there is a mistake in the texts, I want to be able to correct it in all records all at once.  I don't see a reason to make an exception to titles/text incipits and not allow this to be changed. 

Especially now that we are importing data from external sources, it is important that we are able to change this field to have it conform with our data.

Liebe Grüße von
Guido & Jennifer

**Comment by Docudoctor** [comment]
Test.
from Guido

**Comment by lpugin** [comment]
If you all think we can make it editable then we can go for this. But editors need to be aware of the consequences of changing a title value, which as we said can affect thousands of titles.

**Comment by Docudoctor** [comment]
Thank you. We are aware of this. Regularly we would not change already reviewed and corrected titles or text incipits in our older records. In the near future I will focus our opera titles. 
Best,
Guido

**Comment by HirschSt** [comment]
@lpugin never ever count on users discipline; probably we could open the field conditionally (eg sources_cnt < 20)

**Comment by Docudoctor** [comment]
Please review the example below. "Vergiß" should be corrected into "Vergiss":
 
![vergiss](https://cloud.githubusercontent.com/assets/26874482/24649027/eec0b852-1925-11e7-9888-e0c74384bf7f.PNG)

**Comment by lpugin** [comment]
One option to consider here it the addition of a new role. For example, "Senior editor", which would be the only ones allowed to changes these. (Having something similar for cataloguers might very well come on the table when some fields in the authorities are made editable to non editors)

**Comment by Docudoctor** [comment]
@lpugin can you specify your idea, please? We here think of the editors (only members of the Zentralredaktion).

**Comment by xhero** [comment]
What is the status of this? Enabling the field and having a trigger that **automatically resaves** all the sources is doable, do we have a consensus that it is ok?

**Comment by Docudoctor** [comment]
I haven't heard anything since 4 April. Please make titles in Standard Title editable for new entries and for corrections. 
Best regards, 
Guido

**Comment by xhero** [comment]
Ok I'm going to implement it with the relative trigger. Just don't abuse it as it has to re-save all the related sources ;)

**Comment by Docudoctor** [comment]
Thank you. It'll be more a sort of usufruct. :-)

**Comment by xhero** [comment]
I uploaded this in test, and I'm not convinced, because we have linked and unlinked fields. For example, if you modify an standard title that is referred by 240 $a the source can be updated, but if it was referred by the "light weight" link in 031 $t the source is **not** modified, and requires intervention by hand. Then it also breaks the count of the sources in the standard title index.

**Comment by Docudoctor** [comment]
I see. But for now this would be a step forward. I could correct pure filing titles, create new titles and text incipits in the authority file. I would focus on pure titles. If it would be necessary to correct text incipits, I consider to correct it all in 031 by hand. 
May I get also a Muscat test version?

Best,
Guido 

P.S.: We were discussing here a few months ago to separate filing titles from the text incipits putting it into indexes of their own. I guess, this is a solution for the future. Or is it possible for now to link 031 100% with the authority file?

**Comment by xhero** [comment]
What is the status of this?
The feature was added but then reverted to be postponed to 3.6.11 (which is released without), should it be pushed to 3.6.12?

**Comment by Docudoctor** [comment]
Just make this field writeable. So I can start immediately with my work. Or are there any contradictions from your point of view?
Best,
Guido

**Comment by xhero** [comment]
Contradictions no :) I just want to make sure everyone is on board on this big change - which we will need to test throughly on muscat-test.
@lpugin  also suggests that only people with role "editors" can modify the title, is this ok?

**Comment by Docudoctor** [comment]
Yes. Only for editors. :-)
